<?php

namespace SnoozIt\PlatformBundle\DataFixtures\ORM\Localisation;


use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use SnoozIt\PlatformBundle\Entity\Localisation\City;


class LoadVilleThreeData extends AbstractFixture implements OrderedFixtureInterface
{

    public function load(ObjectManager $manager)
    {
        $coteArmorRef   = $this->getReference('departement-cotedarmor');
        $creuseRef      = $this->getReference('departement-creuse');

        $villes_france = array(
            array('departement_id' => $coteArmorRef,'nom' => 'Viersat','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Moutier-Rozeille','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lussat','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Augères','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sermur','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Soumans','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mérinchal','postal' => '23420'),
            array('departement_id' => $coteArmorRef,'nom' => 'Fresselines','postal' => '23450'),
            array('departement_id' => $coteArmorRef,'nom' => 'Janaillat','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Avit-de-Tardes','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Arfeuille-Châtain','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Trois-Fonds','postal' => '23230'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Julien-la-Genête','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pierre-Chérignat','postal' => '23430'),
            array('departement_id' => $coteArmorRef,'nom' => 'Colondannes','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Malval','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Dontreix','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Noth','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Alpinien','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Chapelle-Taillefert','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Pontcharraud','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Brionne','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Vallière','postal' => '23120'),
            array('departement_id' => $coteArmorRef,'nom' => 'Brousse','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Tardes','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Châtelus-Malvaleix','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bosroger','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lupersat','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Chapelle-Saint-Martial','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Vareilles','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chard','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Junien-la-Bregère','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Genouillac','postal' => '23350'),
            array('departement_id' => $coteArmorRef,'nom' => 'Boussac-Bourg','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Vaury','postal' => '23320'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Frion','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mansat-la-Courrière','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Domeyrot','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pierre-de-Fursac','postal' => '23290'),
            array('departement_id' => $coteArmorRef,'nom' => 'Nouziers','postal' => '23350'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Marc-à-Loubaud','postal' => '23460'),
            array('departement_id' => $coteArmorRef,'nom' => 'Gentioux-Pigerolles','postal' => '23340'),
            array('departement_id' => $coteArmorRef,'nom' => 'Maison-Feyne','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Cressat','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Faux-Mazuras','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bazelat','postal' => '23160'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Merd-la-Breuille','postal' => '23100'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chéniers','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Dizier-les-Domaines','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Auge','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Cellette','postal' => '23350'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Victor-en-Marche','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Royère-de-Vassivière','postal' => '23460'),
            array('departement_id' => $coteArmorRef,'nom' => 'Aulon','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Domet','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Silvain-Montaigut','postal' => '23320'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Priest','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'Rougnat','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pardoux-d\'Arnet','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Martial-le-Vieux','postal' => '23100'),
            array('departement_id' => $coteArmorRef,'nom' => 'Auzances','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mautes','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chamberaud','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Forêt-du-Temple','postal' => '23360'),
            array('departement_id' => $coteArmorRef,'nom' => 'Budelière','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Agnant-de-Versillat','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'Villard','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Donzeil','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'Vidaillat','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Pionnat','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Banize','postal' => '23120'),
            array('departement_id' => $coteArmorRef,'nom' => 'Tercillat','postal' => '23350'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Amand-Jartoudeix','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bussière-Nouvelle','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Mazière-aux-Bons-Hommes','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Hilaire-la-Plaine','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bonnat','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Toulx-Sainte-Croix','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Leyrat','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sainte-Feyre-la-Montagne','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lépaud','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Croze','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Sébastien','postal' => '23160'),
            array('departement_id' => $coteArmorRef,'nom' => 'Pontarion','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pierre-le-Bost','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Étienne-de-Fursac','postal' => '23290'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Oradoux-près-Crocq','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bellegarde-en-Marche','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'Néoux','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Villetelle','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Évaux-les-Bains','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Serre-Bussière-Vieille','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Maurice-la-Souterraine','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Celle-Dunoise','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pardoux-Morterolles','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Sulpice-le-Guérétois','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mortroux','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Marsac','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Puy-Malsignat','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Clairavaux','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Champagnat','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lavaveix-les-Mines','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Germain-Beaupré','postal' => '23160'),
            array('departement_id' => $coteArmorRef,'nom' => 'Masbaraud-Mérignat','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Priest-Palus','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Gioux','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mars','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Maixant','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Malleret-Boussac','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Issoudun-Létrieix','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Thauron','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chénérailles','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Dizier-la-Tour','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Dizier-Leyrenne','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Alleyrat','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Blaudeix','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Méasnes','postal' => '23360'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Éloi','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Moutier-d\'Ahun','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Amand','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chambonchard','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'Linard','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Azat-Châtenet','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Anzême','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Peyrat-la-Nonière','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Magnat-l\'Étrange','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Clugnat','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Châtelard','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Priest-la-Feuille','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'Pierrefitte','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Goussaud','postal' => '23430'),
            array('departement_id' => $coteArmorRef,'nom' => 'Soubrebost','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lioux-les-Monges','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Oradoux-de-Chirouze','postal' => '23100'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Compas','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Chaussade','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Pouge','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Flayat','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Poussanges','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Villedieu','postal' => '23340'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mazeirat','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Léger-le-Guérétois','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sagnat','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lizières','postal' => '23240'),
            array('departement_id' => $coteArmorRef,'nom' => 'Ladapeyre','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Arrènes','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Fleurat','postal' => '23320'),
            array('departement_id' => $coteArmorRef,'nom' => 'Beissat','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Peyrabout','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Guéret','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bosmoreau-les-Mines','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Avit-le-Pauvre','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'Crocq','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lourdoueix-Saint-Pierre','postal' => '23360'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Mas-d\'Artige','postal' => '23100'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Yrieix-la-Montagne','postal' => '23460'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Médard-la-Rochette','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Martin-Château','postal' => '23460'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Martial-le-Mont','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lavaufranche','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Maurice-près-Crocq','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Celle-sous-Gouzon','postal' => '23230'),
            array('departement_id' => $coteArmorRef,'nom' => 'Rimondeix','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chambon-Sainte-Croix','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Marc-à-Frongier','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Marien','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Roches','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Charron','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Verneiges','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Reterre','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Bourg-d\'Hem','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Nouzerolles','postal' => '23360'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Souterraine','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Silvain-sous-Toulx','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chamborand','postal' => '23240'),
            array('departement_id' => $coteArmorRef,'nom' => 'Savennes','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Saunière','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Champsanglard','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Yrieix-les-Bois','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Chabrais','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Silvain-Bas-le-Roc','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Vigeville','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Jalesches','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bord-Saint-Georges','postal' => '23230'),
            array('departement_id' => $coteArmorRef,'nom' => 'Jarnages','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Naillat','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bénévent-l\'Abbaye','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Moutier-Malcard','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sardent','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Julien-le-Châtel','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Fransèches','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Laurent','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Chapelle-Baloue','postal' => '23160'),
            array('departement_id' => $coteArmorRef,'nom' => 'Ahun','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Nouzerines','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Fontanières','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sannat','postal' => '23110'),
            array('departement_id' => $coteArmorRef,'nom' => 'Crozant','postal' => '23160'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Loup','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mourioux-Vieilleville','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Hilaire-le-Château','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pardoux-le-Neuf','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pierre-Bellevue','postal' => '23460'),
            array('departement_id' => $coteArmorRef,'nom' => 'Gouzon','postal' => '23230'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Silvain-Bellegarde','postal' => '23190'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chambon-sur-Voueize','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Sulpice-le-Dunois','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Boussac','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Parsac','postal' => '23140'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sous-Parsat','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Maisonnisses','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Quentin-la-Chabanne','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Jouillat','postal' => '23220'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bétête','postal' => '23270'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Bard','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Glénic','postal' => '23380'),
            array('departement_id' => $coteArmorRef,'nom' => 'Aubusson','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Christophe','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Priest-la-Plaine','postal' => '23240'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Chauchet','postal' => '23130'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Fiel','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Mainsat','postal' => '23700'),
            array('departement_id' => $coteArmorRef,'nom' => 'Blessac','postal' => '23200'),
            array('departement_id' => $coteArmorRef,'nom' => 'Ceyroux','postal' => '23210'),
            array('departement_id' => $coteArmorRef,'nom' => 'Féniers','postal' => '23100'),
            array('departement_id' => $coteArmorRef,'nom' => 'Nouhant','postal' => '23170'),
            array('departement_id' => $coteArmorRef,'nom' => 'Montboucher','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lépinas','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Georges-Nigremont','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Malleret','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Courtine','postal' => '23100'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Monteil-au-Vicomte','postal' => '23460'),
            array('departement_id' => $coteArmorRef,'nom' => 'Montaigut-le-Blanc','postal' => '23320'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Martin-Sainte-Catherine','postal' => '23430'),
            array('departement_id' => $coteArmorRef,'nom' => 'Basville','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Agnant-près-Crocq','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bussière-Saint-Georges','postal' => '23600'),
            array('departement_id' => $coteArmorRef,'nom' => 'Le Grand-Bourg','postal' => '23240'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Moreil','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Léger-Bridereix','postal' => '23300'),
            array('departement_id' => $coteArmorRef,'nom' => 'Chavanat','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Sulpice-les-Champs','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'Châtelus-le-Marcheix','postal' => '23430'),
            array('departement_id' => $coteArmorRef,'nom' => 'Faux-la-Montagne','postal' => '23340'),
            array('departement_id' => $coteArmorRef,'nom' => 'Dun-le-Palestel','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Ars','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'Lafat','postal' => '23800'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bussière-Dunoise','postal' => '23320'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Nouaille','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Auriat','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Georges-la-Pouge','postal' => '23250'),
            array('departement_id' => $coteArmorRef,'nom' => 'La Villeneuve','postal' => '23260'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Michel-de-Veisse','postal' => '23480'),
            array('departement_id' => $coteArmorRef,'nom' => 'Azerables','postal' => '23160'),
            array('departement_id' => $coteArmorRef,'nom' => 'Saint-Pardoux-les-Cards','postal' => '23150'),
            array('departement_id' => $coteArmorRef,'nom' => 'Sainte-Feyre','postal' => '23000'),
            array('departement_id' => $coteArmorRef,'nom' => 'Gartempe','postal' => '23320'),
            array('departement_id' => $coteArmorRef,'nom' => 'Bourganeuf','postal' => '23400'),
            array('departement_id' => $coteArmorRef,'nom' => 'Felletin','postal' => '23500'),
            array('departement_id' => $coteArmorRef,'nom' => 'Ajain','postal' => '23380'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Barthélemy-de-Bellegarde','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Capraise-de-Lalinde','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Bayac','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'La Tour-Blanche','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Monfaucon','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Vitrac','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Beynac-et-Cazenac','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Sencenac-Puy-de-Fourches','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Jory-las-Bloux','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Azerat','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Nexans','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Pomport','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Le Change','postal' => '24640'),
            array('departement_id' => $creuseRef,'nom' => 'Prats-de-Carlux','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Barthélemy-de-Bussière','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Julien-d\'Eymet','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Amand-de-Vergt','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Lolme','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-André-de-Double','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Savignac-de-Miremont','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Eyliac','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Trie','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Bouniagues','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Médard-de-Mussidan','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Chapdeuil','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pantaly-d\'Excideuil','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Bourrou','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Paussac-et-Saint-Vivien','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Priest-les-Fougères','postal' => '24450'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Germain-des-Prés','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Grand-Brassac','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Laveyssière','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Daglan','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Tourtoirac','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Veyrines-de-Domme','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Razac-sur-l\'Isle','postal' => '24430'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Victor','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Peyrignac','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Badefols-sur-Dordogne','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Mouleydier','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Ligueux','postal' => '24460'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Romain-de-Monpazier','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cernin-de-l\'Herm','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Chalais','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Sulpice-de-Roumagnac','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Gageac-et-Rouillac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Salignac-Eyvigues','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Teillots','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Fanlac','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Coursac','postal' => '24430'),
            array('departement_id' => $creuseRef,'nom' => 'Cubjac','postal' => '24640'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Vincent-Jalmoutiers','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Berbiguières','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Marie-de-Chignac','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Just','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Champcevinel','postal' => '24750'),
            array('departement_id' => $creuseRef,'nom' => 'Coux-et-Bigaroque','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Auriac-du-Périgord','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Vincent-de-Cosse','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Nathalène','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Boulazac','postal' => '24750'),
            array('departement_id' => $creuseRef,'nom' => 'Plazac','postal' => '24580'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Michel-de-Montaigne','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Soulaures','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Ribérac','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Atur','postal' => '24750'),
            array('departement_id' => $creuseRef,'nom' => 'Sarlande','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Bars','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Augignac','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Eyzerac','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Vanxains','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Sceau-Saint-Angel','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Michel-de-Double','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Avit-de-Vialard','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Louis-en-l\'Isle','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Limeuil','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pierre-de-Chignac','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Georges-de-Montclard','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Celles','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Sarrazac','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Cantillac','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Simeyrols','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Hilaire-d\'Estissac','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Gout-Rossignol','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Église-Neuve-de-Vergt','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Cazoulès','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Creyssensac-et-Pissot','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Puyrenier','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cirq','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Douzillac','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Lembras','postal' => '24100'),
            array('departement_id' => $creuseRef,'nom' => 'Comberanche-et-Épeluche','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cybranet','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Monpazier','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Manzac-sur-Vern','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Capdrot','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martial-d\'Albarède','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Seurin-de-Prats','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Léon-d\'Issigeac','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Laurent-sur-Manoire','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Meyrals','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Condat-sur-Trincou','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Savignac-les-Églises','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Quinsac','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Razac-d\'Eymet','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Eulalie-d\'Ans','postal' => '24640'),
            array('departement_id' => $creuseRef,'nom' => 'Carlux','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martin-l\'Astier','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Siorac-en-Périgord','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martin-de-Fressengeas','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Urval','postal' => '24480'),
            array('departement_id' => $creuseRef,'nom' => 'Antonne-et-Trigonant','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Lisle','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Boisse','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Aulaye','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Brantôme','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Perdoux','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Mensignac','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Nouaille','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Grun-Bordas','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Chancelade','postal' => '24650'),
            array('departement_id' => $creuseRef,'nom' => 'Coly','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Singleyrac','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Prats-du-Périgord','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Archignac','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Le Lardin-Saint-Lazare','postal' => '24570'),
            array('departement_id' => $creuseRef,'nom' => 'Étouars','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Léon-sur-l\'Isle','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Larzac','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Félix-de-Villadeix','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pardoux-et-Vielvic','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Sigoulès','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Beaumont-du-Périgord','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Ginestet','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Mouzens','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Bassillac','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Rudeau-Ladosse','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Alvère','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Beauronne','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Bonneville-et-Saint-Avit-de-Fumadières','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pardoux-de-Drône','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Montpeyroux','postal' => '24610'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Saint-Jean','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Farges','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Coulounieix-Chamiers','postal' => '24660'),
            array('departement_id' => $creuseRef,'nom' => 'Allemans','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Escoire','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Paul-de-Serre','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Paul-Lizonne','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Cendrieux','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Faurilles','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Vézac','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Médard-d\'Excideuil','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Orse','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Villac','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martin-le-Pin','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Bardou','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-André-d\'Allas','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Veyrines-de-Vergt','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Fonroque','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Paunat','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Michel-de-Villadeix','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Castelnaud-la-Chapelle','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Fleurac','postal' => '24580'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Jean-d\'Ataux','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Le Buisson-de-Cadouin','postal' => '24480'),
            array('departement_id' => $creuseRef,'nom' => 'Minzac','postal' => '24610'),
            array('departement_id' => $creuseRef,'nom' => 'Bourniquel','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Laurent-des-Bâtons','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Jory-de-Chalais','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Géry','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Sulpice-de-Mareuil','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Faux','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Milhac-de-Nontron','postal' => '24470'),
            array('departement_id' => $creuseRef,'nom' => 'Le Pizou','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Marcel-du-Périgord','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Lalinde','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Beleymas','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Crépin-et-Carlucet','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Nantheuil','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Beaussac','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Marquay','postal' => '24620'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Sauveur','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pancrace','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pompont','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Vélines','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Cunèges','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pardoux-la-Rivière','postal' => '24470'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Amand-de-Belvès','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Église-Neuve-d\'Issac','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Campsegret','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Bourg-du-Bost','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Port-Sainte-Foy-et-Ponchapt','postal' => '33220'),
            array('departement_id' => $creuseRef,'nom' => 'Audrix','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Groléjac','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Faucher','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Georges-Blancaneix','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Julien-de-Lampon','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Veyrignac','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Montcaret','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Amand-de-Coly','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Aquilin','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Segonzac','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Anlhiac','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Avit-Sénieur','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Lamothe-Montravel','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Aubin-de-Nabirat','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Raphaël','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Bourg-des-Maisons','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Chourgnac','postal' => '24640'),
            array('departement_id' => $creuseRef,'nom' => 'Coutures','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Flaugeac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Varennes','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Mazeyrolles','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Vincent-le-Paluel','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Aubin-de-Cadelech','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Ribagnac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Journiac','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Romain-et-Saint-Clément','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Gaugeac','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Bézenac','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Lèches','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Eulalie-d\'Eymet','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Mauzac-et-Grand-Castang','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Aubin-de-Lanquais','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Temple-Laguyon','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'La Roque-Gageac','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Léguillac-de-Cercles','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cassien','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Belvès','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Vieux-Mareuil','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Petit-Bersac','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Nanteuil-Auriac-de-Bourzac','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Orliaguet','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Bertric-Burée','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Calès','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Puymangou','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Granges-d\'Ans','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Clermont-d\'Excideuil','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Lanquais','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Liorac-sur-Louyre','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Périgueux','postal' => '24000'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Sabine-Born','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Limeyrat','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Siorac-de-Ribérac','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Jean-d\'Eyraud','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martial-de-Nabirat','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Le Bugue','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Cherval','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Champs-Romain','postal' => '24470'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Méard-de-Gurçon','postal' => '24610'),
            array('departement_id' => $creuseRef,'nom' => 'Ménesplet','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Montazeau','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Peyzac-le-Moustier','postal' => '24620'),
            array('departement_id' => $creuseRef,'nom' => 'Pazayac','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Mondane','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Proissans','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Rémy','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Sarlat-la-Canéda','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martin-de-Ribérac','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Salles-de-Belvès','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Geyrac','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Julien-de-Bourdeilles','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Couze-et-Saint-Front','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Grives','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Cornille','postal' => '24750'),
            array('departement_id' => $creuseRef,'nom' => 'La Rochebeaucourt-et-Argentine','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Géraud-de-Corps','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Carsac-de-Gurson','postal' => '24610'),
            array('departement_id' => $creuseRef,'nom' => 'Issac','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Avit-Rivière','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'La Gonterie-Boulouneix','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Graulges','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Connezac','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Monmarvès','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Salon','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Angoisse','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Génis','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Corgnac-sur-l\'Isle','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cyprien','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Lempzours','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Front-de-Pradoux','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Nabirat','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Thenon','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Villars','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Nadaillac','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Nailhac','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Carves','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Radegonde','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Innocence','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Capraise-d\'Eymet','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Borrèze','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Douchapt','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Château-l\'Évêque','postal' => '24460'),
            array('departement_id' => $creuseRef,'nom' => 'Vaunac','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Bergerac','postal' => '24100'),
            array('departement_id' => $creuseRef,'nom' => 'Moulin-Neuf','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Jumilhac-le-Grand','postal' => '24630'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Geniès','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Trélissac','postal' => '24750'),
            array('departement_id' => $creuseRef,'nom' => 'Verteillac','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Villefranche-du-Périgord','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Villamblard','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Campagnac-lès-Quercy','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Méard-de-Drône','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Cause-de-Clérans','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Marsaneix','postal' => '24750'),
            array('departement_id' => $creuseRef,'nom' => 'Conne-de-Labarde','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Biras','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Verdon','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Pezuls','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Cercles','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Besse','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Tamniès','postal' => '24620'),
            array('departement_id' => $creuseRef,'nom' => 'Marcillac-Saint-Quentin','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Valeuil','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Fouleix','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Nastringues','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Teyjat','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Cours-de-Pile','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Alles-sur-Dordogne','postal' => '24480'),
            array('departement_id' => $creuseRef,'nom' => 'Prigonrieux','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'La Bachellerie','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Nanthiat','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Saud-Lacoussière','postal' => '24470'),
            array('departement_id' => $creuseRef,'nom' => 'Chassaignes','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Antoine-de-Breuilh','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Champeaux-et-la-Chapelle-Pommier','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Vincent-de-Connezac','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Agne','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Monmadalès','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Croix-de-Mareuil','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Jean-de-Côle','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Firbeix','postal' => '24450'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cyr-les-Champagnes','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Monestier','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Dussac','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Montrem','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Félix-de-Bourdeilles','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Lacropte','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Montmoreau','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Laurent-des-Hommes','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Maime-de-Péreyrol','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Grèzes','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Excideuil','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Échourgnac','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Gabillou','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'La Jemaye','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Lamonzie-Saint-Martin','postal' => '24680'),
            array('departement_id' => $creuseRef,'nom' => 'Beaupouyet','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Lavaur','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'La Cassagne','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'La Coquille','postal' => '24450'),
            array('departement_id' => $creuseRef,'nom' => 'Champagne-et-Fontaine','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Germain-et-Mons','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Rouffignac-Saint-Cernin-de-Reilhac','postal' => '24580'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Antoine-Cumond','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Vincent-sur-l\'Isle','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Sadillac','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Allas-les-Mines','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Busserolles','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Mescoules','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Chenaud','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Valojoulx','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Ponteyraud','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Servanches','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Savignac-Lédrier','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Loubejac','postal' => '24550'),
            array('departement_id' => $creuseRef,'nom' => 'Domme','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Queyssac','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Fossemagne','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Naussannes','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Brouchaud','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Foy-de-Belvès','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Cherveix-Cubas','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Saussignac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Villetoureix','postal' => '24600'),
            array('departement_id' => $creuseRef,'nom' => 'Mussidan','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Crépin-d\'Auberoche','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Champniers-et-Reilhac','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Labouquerie','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Paulin','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'Montignac','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Abjat-sur-Bandiat','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Jaure','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Mialet','postal' => '24450'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Laurent-la-Vallée','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Mayac','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Ajat','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Montaut','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Festalemps','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Mauzens-et-Miremont','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Campagne','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'La Dornac','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Foy-de-Longas','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Félix-de-Reillac-et-Mortemart','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Biron','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Bourgnac','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Monsac','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Hautefaye','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Jean-d\'Estissac','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Rouffignac-de-Sigoulès','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Castels','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Montagnac-d\'Auberoche','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Sagelat','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Monsec','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Pontours','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'La Douze','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Monsaguel','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Montpon-Ménestérol','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Cernin-de-Labarde','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Razac-de-Saussignac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Salagnac','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Carsac-Aillac','postal' => '24200'),
            array('departement_id' => $creuseRef,'nom' => 'Plaisance','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Preyssac-d\'Excideuil','postal' => '24160'),
            array('departement_id' => $creuseRef,'nom' => 'Chalagnac','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Rabier','postal' => '24210'),
            array('departement_id' => $creuseRef,'nom' => 'Neuvic','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Piégut-Pluviers','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Manaurie','postal' => '24620'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Gonaguet','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Fraisse','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Cénac-et-Saint-Julien','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Bouillac','postal' => '24480'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Estèphe','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Orliac','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Thiviers','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Lussas-et-Nontronneau','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Nontron','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Clermont-de-Beauregard','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Maurens','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Coulaures','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Thonac','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martial-de-Valette','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Bourdeilles','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Mareuil','postal' => '24340'),
            array('departement_id' => $creuseRef,'nom' => 'Parcoul','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Bussac','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Julien-de-Crempse','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Jayac','postal' => '24590'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Grésignac','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Tursac','postal' => '24620'),
            array('departement_id' => $creuseRef,'nom' => 'Champagnac-de-Belair','postal' => '24530'),
            array('departement_id' => $creuseRef,'nom' => 'Trémolat','postal' => '24510'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Front-la-Rivière','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Molières','postal' => '24480'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Aubareil','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pierre-de-Frugie','postal' => '24450'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Privat-des-Prés','postal' => '24410'),
            array('departement_id' => $creuseRef,'nom' => 'Le Bourdeix','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Blis-et-Born','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Châtres','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Montagrier','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Chantérac','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Agonac','postal' => '24460'),
            array('departement_id' => $creuseRef,'nom' => 'La Feuillade','postal' => '19600'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Front-d\'Alemps','postal' => '24460'),
            array('departement_id' => $creuseRef,'nom' => 'Lamonzie-Montastruc','postal' => '24520'),
            array('departement_id' => $creuseRef,'nom' => 'Tocane-Saint-Apre','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'La Force','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Astier','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Marsalès','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Eyzies-de-Tayac-Sireuil','postal' => '24620'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Sulpice-d\'Excideuil','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Antoine-d\'Auberoche','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Badefols-d\'Ans','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Eyvirat','postal' => '24460'),
            array('departement_id' => $creuseRef,'nom' => 'La Boissière-d\'Ans','postal' => '24640'),
            array('departement_id' => $creuseRef,'nom' => 'Vergt','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Beauregard-de-Terrasson','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Serres-et-Montguyard','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Vallereuil','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Séverin-d\'Estissac','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Milhac-d\'Auberoche','postal' => '24330'),
            array('departement_id' => $creuseRef,'nom' => 'Beauregard-et-Bassac','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Lunas','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Négrondes','postal' => '24460'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Paul-la-Roche','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Soudat','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Crépin-de-Richemont','postal' => '24310'),
            array('departement_id' => $creuseRef,'nom' => 'Varaignes','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Mesmin','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Eygurande-et-Gardedeuil','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Chavagnac','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Marnac','postal' => '24220'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Sauveur-Lalande','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Marcory','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Sergeac','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Boisseuilh','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Calviac-en-Périgord','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Issigeac','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Gardonne','postal' => '24680'),
            array('departement_id' => $creuseRef,'nom' => 'Le Fleix','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Nojals-et-Clotte','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'La Roche-Chalais','postal' => '24490'),
            array('departement_id' => $creuseRef,'nom' => 'Eymet','postal' => '24500'),
            array('departement_id' => $creuseRef,'nom' => 'Lusignac','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Marsac-sur-l\'Isle','postal' => '24430'),
            array('departement_id' => $creuseRef,'nom' => 'Baneuil','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Annesse-et-Beaulieu','postal' => '24430'),
            array('departement_id' => $creuseRef,'nom' => 'Bouzic','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Germain-du-Salembre','postal' => '24190'),
            array('departement_id' => $creuseRef,'nom' => 'Fougueyrolles','postal' => '33220'),
            array('departement_id' => $creuseRef,'nom' => 'Condat-sur-Vézère','postal' => '24570'),
            array('departement_id' => $creuseRef,'nom' => 'Douville','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Léon-sur-Vézère','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pierre-d\'Eyraud','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Peyrillac-et-Millac','postal' => '24370'),
            array('departement_id' => $creuseRef,'nom' => 'Pressignac-Vicq','postal' => '24150'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Front-sur-Nizonne','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Bosset','postal' => '24130'),
            array('departement_id' => $creuseRef,'nom' => 'Doissat','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Cladech','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Savignac-de-Nontron','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Laurent-des-Vignes','postal' => '24100'),
            array('departement_id' => $creuseRef,'nom' => 'Hautefort','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Monplaisant','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Coubjours','postal' => '24390'),
            array('departement_id' => $creuseRef,'nom' => 'Colombier','postal' => '24560'),
            array('departement_id' => $creuseRef,'nom' => 'Sarliac-sur-l\'Isle','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pierre-de-Côle','postal' => '24800'),
            array('departement_id' => $creuseRef,'nom' => 'Léguillac-de-l\'Auche','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Chamassy','postal' => '24260'),
            array('departement_id' => $creuseRef,'nom' => 'Sourzac','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Creysse','postal' => '24100'),
            array('departement_id' => $creuseRef,'nom' => 'Aubas','postal' => '24290'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martial-Viveyrol','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Breuilh','postal' => '24380'),
            array('departement_id' => $creuseRef,'nom' => 'Rampieux','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Vivien','postal' => '24230'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martin-des-Combes','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Montferrand-du-Périgord','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Lavalade','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Bussière-Badil','postal' => '24360'),
            array('departement_id' => $creuseRef,'nom' => 'Thénac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Vendoire','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Florimont-Gaumier','postal' => '24250'),
            array('departement_id' => $creuseRef,'nom' => 'Bouteilles-Saint-Sébastien','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'La Chapelle-Montabourlet','postal' => '24320'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Pantaly-d\'Ans','postal' => '24640'),
            array('departement_id' => $creuseRef,'nom' => 'Monbazillac','postal' => '24240'),
            array('departement_id' => $creuseRef,'nom' => 'Vergt-de-Biron','postal' => '24540'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Germain-de-Belvès','postal' => '24170'),
            array('departement_id' => $creuseRef,'nom' => 'Javerlhac-et-la-Chapelle-Saint-Robert','postal' => '24300'),
            array('departement_id' => $creuseRef,'nom' => 'Sainte-Croix','postal' => '24440'),
            array('departement_id' => $creuseRef,'nom' => 'Payzac','postal' => '24270'),
            array('departement_id' => $creuseRef,'nom' => 'Creyssac','postal' => '24350'),
            array('departement_id' => $creuseRef,'nom' => 'Sorges','postal' => '24420'),
            array('departement_id' => $creuseRef,'nom' => 'Terrasson-Lavilledieu','postal' => '24120'),
            array('departement_id' => $creuseRef,'nom' => 'Grignols','postal' => '24110'),
            array('departement_id' => $creuseRef,'nom' => 'Notre-Dame-de-Sanilhac','postal' => '24660'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Étienne-de-Puycorbier','postal' => '24400'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martial-d\'Artenset','postal' => '24700'),
            array('departement_id' => $creuseRef,'nom' => 'Montagnac-la-Crempse','postal' => '24140'),
            array('departement_id' => $creuseRef,'nom' => 'Saint-Martin-de-Gurson','postal' => '24610'),
            array('departement_id' => $creuseRef,'nom' => 'Villefranche-de-Lonchat','postal' => '24610')
        );

        foreach($villes_france as $array => $element) {
            $manager->persist($this->createCity($element['nom'], $element['departement_id'], $element['postal']));
        }

        $manager->flush();
    }

    public function createCity($nom, $reference, $postal)
    {
        $city = new City;

        $city->setNom($nom);
        $city->setDepartement($reference);
        $city->setPostal($postal);

        return $city;
    }

    // Fonction de mise en ordre
    public function getOrder()
    {
        return 5;
    }

}