snoozit_search_engine_catch:
    path: /
    defaults: { _controller: SnoozitPlatformBundle:SearchEngine:catchAdvert }

snoozit_platform_search_result_without_slug:
    path: /r/{region}/c/{category}
    defaults: { _controller: SnoozitPlatformBundle:SearchEngine:searchAdvertResult }

snoozit_platform_search_result_full:
    path: /r/{region}/c/{category}/{slug}
    defaults: { _controller: SnoozitPlatformBundle:SearchEngine:searchAdvertResult}

snoozit_platform_search_result_category:
    path: /c/{category}/{slug}
    defaults: { _controller: SnoozitPlatformBundle:SearchEngine:searchAdvertResult}

snoozit_platform_search_result_region:
    path: /r/{region}/{slug}
    defaults: { _controller: SnoozitPlatformBundle:SearchEngine:searchAdvertResult }

snoozit_platform_search_simple_result:
    path: /{slug}
    defaults: { _controller: SnoozitPlatformBundle:SearchEngine:searchAdvertResult}

