<?php

namespace Snoozit\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileCommentRepository extends EntityRepository
{
}
