<?php

namespace Snoozit\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileCommentToCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileCommentToCommentRepository extends EntityRepository
{
}
